---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unshort
    version: 1.0.0
  name: unshort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unshort
  strategy: {}
  template:
    metadata:
      labels:
        app: unshort
        version: 1.0.0
    spec:
      containers:
        - image: ghcr.io/agravgaard/unshort.link/unshort:latest
          name: unshort
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: true
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
