---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unshort
  name: unshort
spec:
  ports:
    - name: unshort
      port: 8111
      protocol: TCP
      targetPort: 8080
  selector:
    app: unshort
  type: LoadBalancer
status:
  loadBalancer: {}
