---
name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17+
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Generate
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go generate ./...
      - name: Build
        run: |
          cd server
          go build .
      - name: Test
        run: |
          cd server
          go test ./...
      - name: Vet
        run: |
          cd server
          go vet ./...
      - name: Lint
        run: |
          cd server
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.47.1
          ./bin/golangci-lint run
